packages:
  - 'apps/**'
  - 'packages/**'
catalogs:
  dev:
    '@eslint-react/eslint-plugin': ^1.37.3
    '@types/node': ^22.13.11
    eslint: ^9.23.0
    eslint-plugin-format: ^1.0.1
    eslint-plugin-import-x: ^4.9.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react-refresh: ^0.4.19
    eslint-plugin-react-compiler: 19.0.0-beta-aeaed83-20250323
    eslint-plugin-unused-imports: ^4.1.4
    lint-staged: ^15.5.0
    tsx: ^4.19.3
    typescript: ^5.8.2
  prod:
    '@typescript-eslint/eslint-plugin': ^8.27.0
    '@typescript-eslint/parser': ^8.27.0
    eslint-flat-config-utils: ^2.0.1
    globals: ^16.0.0
    local-pkg: ^1.1.1
