# Remove this from your own repo

name: Validate Sanity Template
on:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Sanity Template
        uses: sanity-io/template-validator@e09f3d809a44c9ac771cb35b83d3e63aa22624b7
