# Remove this from your own repo

name: Validate Sanity Template
on:
  push:
    branches: [main]

  pull_request:
    types: [opened, synchronize, reopened]
    # Only consider those paths to trigger the action
    paths:
      - 'packages/**'
      - 'package.json'
      - '*.lock'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '.npmrc'
      - 'tsconfig.base.json'
      - '.prettier*'
      - '.github/**'
      - 'turbo.json'

  # Allows triggering this workflow from GitHub UI
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Sanity Template
        uses: sanity-io/template-validator@6f6003224268499e7361fa848b0c9eed232a2113 # v2.4.3
