# Remove this from your own repo

name: Validate Sanity Template
on:
  push:
    branches: [main]

  pull_request:
    types: [opened, synchronize, reopened]

  # Allows triggering this workflow from GitHub UI
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate Sanity Template
        run: npx --yes @sanity/template-validator
